name: Test work with secrets github

on:
  workflow_dispatch:
    inputs:
      secret_key:
        default: TEST_SECRET_KEY
        description: Name of a secret
        type: string
        required: true
      secret_value:
        default: TEST_SECRET_VALUE
        description: Value of a secret
        type: string
        required: true

jobs:
  update-secret:
    name: Update a Github secret value
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm install --global sodium-native
          echo "NODE_PATH=$(npm root -g)" >> $GITHUB_ENV
      - name: Update secret value
        uses: actions/github-script@v7
        env:
          SECRET_KEY: ${{ inputs.secret_key }}
          SECRET_VALUE: ${{ inputs.secret_value }}
        with:
          result-encoding: string
          # github-token: ${{ env.GITHUB_TOKEN }}
          script: |
              const sodium = require('sodium-native');
              core.info(JSON.stringify(context));
